{
 "title": "FastAPI Dashboard",
 "tags": [
  "fastAPI",
  "DATA-EKS"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(http_requests_total, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler, app_kubernetes_io_instance) (increase(http_requests_total{app_kubernetes_io_instance=~\"$app\", status=\"4xx\"}[1m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}-{{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{app_kubernetes_io_instance=~\"$app\",handler!=\"none\"} / http_request_duration_seconds_count{app_kubernetes_io_instance=~\"$app\",handler!=\"none\"}",
     "legendFormat": "{{ app_kubernetes_io_instance }}-{{ handler }}"
    }
   ]
  },
  {
   "title": "RPS per minutes",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status, app_kubernetes_io_instance) (rate(http_requests_total{app_kubernetes_io_instance=~\"$app\", handler!=\"/\"}[1m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}({{ status }})"
    }
   ]
  },
  {
   "title": "Request per 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, app_kubernetes_io_instance) (rate(http_requests_total{app_kubernetes_io_instance=~\"$app\"}[5m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}({{ status }})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app_kubernetes_io_instance=~\"$app\"}[1m])",
     "legendFormat": "{{ app_kubernetes_io_instance }}({{ instance }})"
    }
   ]
  },
  {
   "title": "Total requests per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (status, app_kubernetes_io_instance) (increase(http_requests_total{app_kubernetes_io_instance=~\"$app\", handler!=\"/\"}[5m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}({{ status }})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app_kubernetes_io_instance=~\"$app\"}",
     "legendFormat": "{{ app_kubernetes_io_instance }}({{ instance }})"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{app_kubernetes_io_instance=~\"$app\", le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{app_kubernetes_io_instance=~\"$app\"}[1m])",
     "legendFormat": "{{ app }}-{{ handler }}"
    }
   ]
  },
  {
   "title": "Total requests per minutes",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{app_kubernetes_io_instance=~\"$app\", handler!=\"/\"}[1m])) by (handler, status)",
     "legendFormat": "{{ handler }}({{ status }})"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 44 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{app_kubernetes_io_instance=~\"$app\", handler!=\"none\"}[1m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}-{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 53 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{app_kubernetes_io_instance=~\"$app\", handler!=\"none\"}[1m]))",
     "legendFormat": "{{ app_kubernetes_io_instance }}-{{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, app) (rate(http_requests_total{app=~\"$app\", status=\"4xx\"}[1m]))",
     "legendFormat": "{{ app }}-{{ handler }}"
    }
   ]
  }
 ]
}