{
 "title": "Kafka Exporter Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_brokers, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{app_kubernetes_io_instance ='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{argocd_argoproj_io_instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Kafka CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{app_kubernetes_io_instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{app_kubernetes_io_instance=\"$instance\"}",
     "legendFormat": "{{instance}}-Heap"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{app_kubernetes_io_instance=\"$instance\"}",
     "legendFormat": "{{instance}}-No Heap"
    }
   ]
  },
  {
   "title": "Memory Usage Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instance-[0-9]+\", container=\"\"}) by (pod, container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Volume Size Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-$instance-[0-9]+\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$instance-[0-9]+\"}[1m])",
     "legendFormat": "{{pod}} - receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$instance-[0-9]+\"}[1m])",
     "legendFormat": "{{pod}} - transmit"
    }
   ]
  },
  {
   "title": "Disk Write Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_kafkaserver_total_linux_disk_write_bytes_value{app_kubernetes_io_instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_kafkaserver_total_linux_disk_read_bytes_value{app_kubernetes_io_instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Messages Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{app_kubernetes_io_instance=\"$instance\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{app_kubernetes_io_instance=~'$instance',topic=~\"$topic\"}[1m])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{app_kubernetes_io_instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Byte In per topic and broker",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesinpersec_count{app_kubernetes_io_instance=\"$instance\", topic=~\"$topic\"}[1m])",
     "legendFormat": "{{topic}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Byte Out per topic and broker",
   "type": "graph",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesoutpersec_count{app_kubernetes_io_instance=\"$instance\", topic=~\"$topic\"}[1m])",
     "legendFormat": "{{topic}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{app_kubernetes_io_instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}