{
 "title": "Kafka Connect Dashboard",
 "tags": [
  "Kafka",
  "Connect"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Tasks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_running_task_count",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Task Status per Connector",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_total_task_count",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_running_task_count",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_failed_task_count",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_paused_task_count",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_failed_task_count",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Kafak Connect Cluster Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Kafka connect CPU Usage",
   "type": "timeseries",
   "description": "The recent cpu usage for the whole system",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kafka\", pod=~\"^kafka-connect-.+\", container=\"cp-kafka-connect-server\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Worker",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"kafka-connect-.+\", container=\"\"}) by (pod, container)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_used{app=\"cp-kafka-connect\"}",
     "legendFormat": "{{pod}} - heap"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"kafka-connect-.+\"}[1m])",
     "legendFormat": "{{pod}} - receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"kafka-connect-.+\"}[1m])",
     "legendFormat": "{{pod}} - transmit"
    }
   ]
  },
  { "title": "MongoDB Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Poll durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_in_task_poll_duration_ms{}[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Change Stream Lag",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "com_mongodb_kafka_connect_source_task_metrics_latest_mongodb_time_difference_secs{task=~\".+change-stream.+\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "framework durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_in_connect_framework_duration_ms{}[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "records in per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_records{}[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "failed records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "increase(com_mongodb_kafka_connect_source_task_metrics_records[1m]) - increase(com_mongodb_kafka_connect_source_task_metrics_records_filtered[1m]) - increase(com_mongodb_kafka_connect_source_task_metrics_records_acknowledged[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "bytes read in per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_mongodb_bytes_read{}[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "average message size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_mongodb_bytes_read{}[1m]) / rate(com_mongodb_kafka_connect_source_task_metrics_records{}[1m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "Kafak Connecter Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Legacy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka connect CPU Usage",
     "type": "timeseries",
     "description": "The recent cpu usage for the whole system",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "java_lang_operatingsystem_systemcpuload{app=\"cp-kafka-connect\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Memory Usage",
     "type": "stat",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_memory_heapmemoryusage_used{app=\"cp-kafka-connect\"}",
       "legendFormat": "{{instance}}-Heap"
      },
      {
       "expr": "java_lang_memory_nonheapmemoryusage_used{app=\"cp-kafka-connect\"}",
       "legendFormat": "{{instance}}-NoHeap"
      }
     ]
    }
   ]
  }
 ]
}